### ISSUE TITLE
Need an event listener for Enter key on contenteditable element.

### ISSUE THREAD

**Issue by mngatewood** [CharlesY712/2DoBox#18]

**Comment by mngatewood** [comment]
Not as easy as I thought.

**Comment by CharlesY712** [comment]
Cant figure out how to make an "on keydown" inside of a "click" listener. Then tried an independant event listener for keydown, it wouldnt register.

**Comment by mngatewood** [comment]
I tried the same thing this morning with the same result.  I propose we close this.

**Comment by CharlesY712** [comment]
Figured it out! Yay!
